package br.com.sulamerica.gto.rule;

import br.com.sulamerica.gto.model.Procedimento;

rule "Procedimento nao ativou regra"
    dialect "mvel"
    enabled true
    no-loop true
    agenda-group "regras-soberanas"
    salience -10
    
    when
        proc: Procedimento (registrosAnaliseEletronica == null)
    then
        System.out.println("Regra soberana ativada");
        proc.setAnalisadoEletronicamente(true);
        proc.setStatusPagAposAnaiseEletronica("Análise");
end

