package br.com.sulamerica.gto.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AnaliseEletronica implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Mensagens mais amigáveis da análise eletrônica")
	private String mensagem;
	@org.kie.api.definition.type.Label("Status do pagamento")
	private java.lang.String statusPagamento;
	@org.kie.api.definition.type.Label("Código do motivo")
	private int motivo;

	@org.kie.api.definition.type.Label(value = "Objeto da análise eletrônica")
	private java.lang.String objetoAnalise;

	public AnaliseEletronica() {
	}

	public java.lang.String getStatusPagamento() {
		return this.statusPagamento;
	}

	public void setStatusPagamento(java.lang.String statusPagamento) {
		this.statusPagamento = statusPagamento;
	}

	public int getMotivo() {
		return this.motivo;
	}

	public void setMotivo(int motivo) {
		this.motivo = motivo;
	}

	public java.lang.String getMensagem() {
		return this.mensagem;
	}

	public void setMensagem(java.lang.String mensagem) {
		this.mensagem = mensagem;
	}

	public java.lang.String getObjetoAnalise() {
		return this.objetoAnalise;
	}

	public void setObjetoAnalise(java.lang.String objetoAnalise) {
		this.objetoAnalise = objetoAnalise;
	}

	public AnaliseEletronica(java.lang.String mensagem,
			java.lang.String statusPagamento, int motivo,
			java.lang.String objetoAnalise) {
		this.mensagem = mensagem;
		this.statusPagamento = statusPagamento;
		this.motivo = motivo;
		this.objetoAnalise = objetoAnalise;
	}

}