package br.com.sulamerica.gto.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dentista implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Dentista() {
    }




}