package br.com.sulamerica.gto.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Empresa implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Contrato da empresa")
	private java.lang.String contrato;
	@org.kie.api.definition.type.Label("Código do grupo")
	private int codGrupo;

	@org.kie.api.definition.type.Label(value = "Produto do contratante")
	private int codProduto;

	public Empresa() {
	}

	public java.lang.String getContrato() {
		return this.contrato;
	}

	public void setContrato(java.lang.String contrato) {
		this.contrato = contrato;
	}

	public int getCodGrupo() {
		return this.codGrupo;
	}

	public void setCodGrupo(int codGrupo) {
		this.codGrupo = codGrupo;
	}

	public int getCodProduto() {
		return this.codProduto;
	}

	public void setCodProduto(int codProduto) {
		this.codProduto = codProduto;
	}

	public Empresa(java.lang.String contrato, int codGrupo, int codProduto) {
		this.contrato = contrato;
		this.codGrupo = codGrupo;
		this.codProduto = codProduto;
	}

}