package br.com.sulamerica.gto.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Empresa implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Código do grupo")
	private int codGrupo;

	@org.kie.api.definition.type.Label("Produto do contratante")
	private int codProduto;

	@org.kie.api.definition.type.Label(value = "Código do contrato")
	private int codContrato;

	public Empresa() {
	}

	public int getCodGrupo() {
		return this.codGrupo;
	}

	public void setCodGrupo(int codGrupo) {
		this.codGrupo = codGrupo;
	}

	public int getCodProduto() {
		return this.codProduto;
	}

	public void setCodProduto(int codProduto) {
		this.codProduto = codProduto;
	}

	public int getCodContrato() {
		return this.codContrato;
	}

	public void setCodContrato(int codContrato) {
		this.codContrato = codContrato;
	}

	public Empresa(int codGrupo, int codProduto, int codContrato) {
		this.codGrupo = codGrupo;
		this.codProduto = codProduto;
		this.codContrato = codContrato;
	}

}