package br.com.sulamerica.gto.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Data em que ocorreu a auditoria eletrônica")
	private java.time.LocalDate dataAuditoriaEletronica;
	@org.kie.api.definition.type.Label("Data até quando a gui estará válida")
	private java.time.LocalDate dataValidade;
	@org.kie.api.definition.type.Label("Canal de entrada")
	private java.lang.String canal;

	@org.kie.api.definition.type.Label("Lista de procedimentos")
	private java.util.List<br.com.sulamerica.gto.model.Procedimento> procedimentos;

	@org.kie.api.definition.type.Label("Prestador de serviço")
	private br.com.sulamerica.gto.model.Prestador prestador;

	private br.com.sulamerica.gto.model.Empresa empresa;

	@org.kie.api.definition.type.Label("Informações do segurado")
	private br.com.sulamerica.gto.model.Segurado segurado;

	public GTO() {
	}

	public java.time.LocalDate getDataAuditoriaEletronica() {
		return this.dataAuditoriaEletronica;
	}

	public void setDataAuditoriaEletronica(
			java.time.LocalDate dataAuditoriaEletronica) {
		this.dataAuditoriaEletronica = dataAuditoriaEletronica;
	}

	public java.time.LocalDate getDataValidade() {
		return this.dataValidade;
	}

	public void setDataValidade(java.time.LocalDate dataValidade) {
		this.dataValidade = dataValidade;
	}

	public java.lang.String getCanal() {
		return this.canal;
	}

	public void setCanal(java.lang.String canal) {
		this.canal = canal;
	}

	public java.util.List<br.com.sulamerica.gto.model.Procedimento> getProcedimentos() {
		return this.procedimentos;
	}

	public void setProcedimentos(
			java.util.List<br.com.sulamerica.gto.model.Procedimento> procedimentos) {
		this.procedimentos = procedimentos;
	}

	public br.com.sulamerica.gto.model.Prestador getPrestador() {
		return this.prestador;
	}

	public void setPrestador(br.com.sulamerica.gto.model.Prestador prestador) {
		this.prestador = prestador;
	}

	public br.com.sulamerica.gto.model.Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(br.com.sulamerica.gto.model.Empresa empresa) {
		this.empresa = empresa;
	}

	public br.com.sulamerica.gto.model.Segurado getSegurado() {
		return this.segurado;
	}

	public void setSegurado(br.com.sulamerica.gto.model.Segurado segurado) {
		this.segurado = segurado;
	}

	public GTO(
			java.time.LocalDate dataAuditoriaEletronica,
			java.time.LocalDate dataValidade,
			java.lang.String canal,
			java.util.List<br.com.sulamerica.gto.model.Procedimento> procedimentos,
			br.com.sulamerica.gto.model.Prestador prestador,
			br.com.sulamerica.gto.model.Empresa empresa,
			br.com.sulamerica.gto.model.Segurado segurado) {
		this.dataAuditoriaEletronica = dataAuditoriaEletronica;
		this.dataValidade = dataValidade;
		this.canal = canal;
		this.procedimentos = procedimentos;
		this.prestador = prestador;
		this.empresa = empresa;
		this.segurado = segurado;
	}

}